spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_worker
    username: kamkendra
    password: myKam
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
server:
  port: 8070       